server.port=8888
spring.application.name=config-server

spring.profiles.active=native

#spring.cloud.config.server.native.search-locations=file:///C:/Users/yaoqi/OneDrive/Desktop/weather/properties

management.endpoints.web.exposure.include=*

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

encrypt.key=RJ2+VX1+xDbCH1s8+0BFR++N+xqXcpIp
spring.cloud.config.server.native.search-locations=classpath:/config

spring.security.user.name=configuser
spring.security.user.password=configpassword
spring.security.user.roles=SYSTEM

management.endpoint.health.show-details=always

# Enable Prometheus endpoint
management.metrics.export.prometheus.enabled=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true

# Add service-specific tags
management.metrics.tags.application=${spring.application.name}

# ????? Keystore & Jasypt ?????
server.ssl.key-store=classpath:config-service.p12
server.ssl.key-store-password=ENC(RJ2+VX1+xDbCH1s8+0BFR++N+xqXcpIp)
#server.ssl.key-store-password=123456
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=config-service

jasypt.encryptor.password=${JASYPT_ENCRYPTOR_PASSWORD:RJ2+VX1+xDbCH1s8+0BFR++N+xqXcpIp}


# ????? Swagger/OpenAPI ?????
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html