server.port=8082
spring.application.name=search

# Eureka client config
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Hystrix settings
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=5000
hystrix.threadpool.default.coreSize=20
hystrix.threadpool.default.maxQueueSize=500
hystrix.threadpool.default.queueSizeRejectionThreshold=500

# Ribbon settings
ribbon.ConnectTimeout=3000
ribbon.ReadTimeout=60000